name: Node.js CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    if: false # @todo: disable temporarily
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd aofl-js-packages
          npm install

      - name: Run lint
        run: |
          cd aofl-js-packages
          npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd aofl-js-packages
          npm install

      - name: Download and Start Selenium Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.0.0/selenium-server-4.0.0.jar -O selenium-server.jar
          java -jar selenium-server.jar standalone --host 127.0.0.1 --port 4444 &
        shell: bash

      - name: Wait for Selenium to start
        run: |
          until curl -s http://127.0.0.1:4444/wd/hub/status | grep '"ready":true' > /dev/null; do
            echo "Waiting for Selenium..."
            sleep 2
          done

      - name: Run tests
        run: |
          cd aofl-js-packages
          npm test -- --debug
        continue-on-error: true

      - name: Display test results
        # if: failure()
        run: |
          find aofl-js-packages/logs/unit-test -type f -exec cat {} +
